development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: GOlf_development
  pool: 5
  username: root
  password: Fifty50
  host: localhost
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: Golf_test
  pool: 5
  username: root
  password: Fifty50
  host: 127.0.0.1

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: GOlf_production
  pool: 5
  username: root
  password: Fifty50
  host: localhost





























